# Generated by Django 5.2.17 on 2026-09-24 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("canonical", models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="DailyAIUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("scope", models.CharField(max_length=48)),
                ("day", models.DateField()),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("input_tokens", models.PositiveBigIntegerField(default=0)),
                ("output_tokens", models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.UUIDField()),
                ("kind", models.CharField(max_length=16)),
                ("fingerprint", models.CharField(max_length=64)),
                ("response", models.JSONField(null=True)),
                ("status_code", models.PositiveSmallIntegerField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="chatsession",
            name="busy_token",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="busy_until",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="analysis",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="analysis_token",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="analysis_until",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="analysis_version",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="sha256",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="mediafile",
            name="size",
            field=models.PositiveIntegerField(),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["user", "-updated_at", "-id"], name="chatbot_cha_user_id_0dd4d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["session", "id"], name="chatbot_mes_session_04d24e_idx"),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(fields=("session",), name="one_booking_per_session"),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["pending", "confirmed", "cancelled"])),
                name="booking_valid_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatsession",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["in_progress", "diagnosed", "booked"])),
                name="session_valid_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="diagnosis",
            constraint=models.UniqueConstraint(
                fields=("session",), name="one_diagnosis_per_session"
            ),
        ),
        migrations.AddConstraint(
            model_name="diagnosis",
            constraint=models.CheckConstraint(
                condition=models.Q(("confidence__gte", 0), ("confidence__lte", 1)),
                name="diagnosis_confidence_range",
            ),
        ),
        migrations.AddField(
            model_name="accountemail",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyaiusage",
            constraint=models.UniqueConstraint(fields=("scope", "day"), name="daily_ai_scope"),
        ),
        migrations.AddField(
            model_name="operation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="operation",
            constraint=models.UniqueConstraint(
                fields=("user", "kind", "key"), name="operation_idempotency"
            ),
        ),
    ]
