# Generated by Django 5.2.17 on 2026-09-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0003_account_emails"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoredObject",
            fields=[
                ("name", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("content", models.BinaryField()),
                ("size", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
